/**
 * @TYPES
 * ===============================================
 * APPOINTMENTS
 */
export const APPOINTMENTS_FETCH_ALL = 'APPOINTMENTS_FETCH_ALL'
export const APPOINTMENTS_FETCH_BY_ID = 'APPOINTMENTS_FETCH_BY_ID'
export const APPOINTMENTS_FETCH_BY_CHILD = 'APPOINTMENTS_FETCH_BY_CHILD'
export const APPOINTMENTS_CREATE = 'APPOINTMENTS_CREATE'
export const APPOINTMENTS_GET_SCHEDULE = 'APPOINTMENTS_GET_SCHEDULE'
export const APPOINTMENTS_UPDATE_DATE = 'APPOINTMENTS_UPDATE_DATE'
export const APPOINTMENTS_UPDATE_STATUS = 'APPOINTMENTS_UPDATE_STATUS'
export const APPOINTMENTS_ERROR = 'APPOINTMENTS_ERROR'

/**
 * @TYPES
 * ===============================================
 * CHILD
 */
export const CHILD_REGISTER = 'CHILD_REGISTER'
export const CHILD_FETCH_ALL = 'CHILD_FETCH_ALL'
export const CHILD_GET_BY_ID = 'CHILD_GET_BY_ID'
export const CHILD_GET_BY_EMAIL = 'CHILD_GET_BY_EMAIL'
export const CHILD_FIND= 'CHILD_FIND'
export const CHILD_ERROR = 'CHILD_ERROR'

/**
 * @TYPES
 * ===============================================
 * LOOKUP
 */
export const LOOKUP_GENDER = 'LOOKUP_GENDER'
export const LOOKUP_MARITAL_STATUS = 'LOOKUP_MARITAL_STATUS'
export const LOOKUP_ROLE = 'LOOKUP_ROLE'
export const LOOKUP_RELATIONSHIP = 'LOOKUP_RELATIONSHIP'
export const LOOKUP_COUNTY = 'LOOKUP_COUNTY'
export const LOOKUP_FACILITY_LEVEL = 'LOOKUP_FACILITY_LEVEL'
export const LOOKUP_APPOINTMENT_STATUS = 'LOOKUP_APPOINTMENT_STATUS'
export const LOOKUP_ERROR = 'LOOKUP_ERROR'


/**
 * @TYPES
 * ===============================================
 * IMMUNIZATION
 */
export const IMMUNIZATION_FETCH_ALL = 'IMMUNIZATION_FETCH_ALL'
export const IMMUNIZATION_ERROR = 'IMMUNIZATION_ERROR'

/**
 * @TYPES
 * ===============================================
 * AUTHENTICATE
 */
export const AUTHENTICATION = 'AUTHENTICATION'
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
export const UNAUTHORISED_ERROR = 'UNAUTHORISED_ERROR'